# Site settings
title: "Vitor de Lima Cirqueira"
description: "Curr√≠culo Vitae"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vitor de Lima Cirqueira"
#resume_title:                   ""
resume_contact_email:
  "vitorlimacir@outlook.com"
resume_header_contact_info: "(62)98221-7083 | vitorlimacir@outlook.com"
resume_header_intro: "<p>22 anos / Telefone:(62)98221-7083 / E-mail: vitorlimacir@outlook.com / vitorcirqueira@gmail.com</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/vitorlc"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/vitor.lima.967"
  resume_linkedin_url:          "https://www.linkedin.com/in/vitor-de-lima-cirqueira-4b6062b1/"
  resume_instagram_url:         "https://www.instagram.com/vitor.lc/"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
